#pragma once

#include <Uefi.h>

#define EFI_FILE_MODE_READ 0x0000000000000001ULL

struct EFI_FILE_PROTOCOL;
using EFI_FILE_OPEN = EFI_STATUS(EFIAPI*)(
    EFI_FILE_PROTOCOL*,
    EFI_FILE_PROTOCOL**,
    CHAR16*,
    UINT64,
    UINT64);
using EFI_FILE_CLOSE = EFI_STATUS(EFIAPI*)(EFI_FILE_PROTOCOL*);
using EFI_FILE_DELETE = EFI_STATUS(EFIAPI*)(EFI_FILE_PROTOCOL*);
using EFI_FILE_READ = EFI_STATUS(EFIAPI*)(
    EFI_FILE_PROTOCOL*, UINTN*, VOID*);
using EFI_FILE_WRITE = EFI_STATUS(EFIAPI*)(
    EFI_FILE_PROTOCOL*, UINTN*, VOID*);

struct EFI_FILE_PROTOCOL {
  UINT64 Revision;
  EFI_FILE_OPEN Open;
  EFI_FILE_CLOSE Close;
  EFI_FILE_DELETE Delete;
  EFI_FILE_READ Read;
  EFI_FILE_WRITE Write;
};

struct EFI_SIMPLE_FILE_SYSTEM_PROTOCOL;
using EFI_SIMPLE_FILE_SYSTEM_PROTOCOL_OPEN_VOLUME = EFI_STATUS(EFIAPI*)(
    EFI_SIMPLE_FILE_SYSTEM_PROTOCOL*,
    EFI_FILE_PROTOCOL**);

struct EFI_SIMPLE_FILE_SYSTEM_PROTOCOL {
  UINT64 Revision;
  EFI_SIMPLE_FILE_SYSTEM_PROTOCOL_OPEN_VOLUME OpenVolume;
};

extern EFI_GUID gEfiSimpleFileSystemProtocolGuid;
